export class UserModel{
  id: any;
  firstname? : string;
  lastname?: string;
  username?:string;
  phonenumber?:string;
  email?:string;
  password?:string;
  role?:string;
  active? : boolean;
  theory_id? : number;
  religion_id? : number;
  ethnicity_id? : number;
  govermentposition_id?: number;
  organizationposition_id? : number;
  code?:string;
  birthday:any;
  date_start_work:any;
  born_village_id?:number;
  born_district_id?:number;
  born_province_id?:number;
  village_id?:number;
  district_id?:number;
  province_id?:number;
  subject_id?:number;
  youth_date?:any;
  committee_date?:any;
  woman_date:any;
  reverve_party_date:any;
  perfect_party_date:any;
  party_position_id?:number;
  organiztion_position_id?:number;
  govement_position_id?:number;
  note?:string;
  profile?:File;
  mass_id?:number;
  createdDate:any;
  datestartwork?: any;
  youthdate?: any;
  committeedate?: any;
  womandate?: any;
  revervepartydate?: any;
  perfectpartydate?: any;
  checkimg?: any;
  ethnicity?: null;
  religion?: null;
  bornvillage?: string;
  borndistrict?: string;
  bornprovince?: string;
  village?: string;
  district?: string;
  province?: string;
  subject?: string;
  theory?: string;
  party?: string;
  organization?: string;
  goverment?: string;
  massorganization?: string;
  }